/* May Bike V15.5 - Hotfix relatorios v2 */
(function(){'use strict';
function arr(k){if(!Array.isArray(st[k]))st[k]=[];return st[k]}
window.upsert=function(k,o){let a=arr(k),i=a.findIndex(x=>x&&x.id===o.id);if(i>=0)a[i]={...a[i],...o};else a.push(o);return o};
window.del=function(k,id){if(!confirm('Deseja realmente excluir este registro?'))return;st[k]=arr(k).filter(x=>x&&x.id!==id);save()};
window.addCaixa=function(tipo,valor,desc,cat,forma){arr('caixa').push({id:uid(),data:today(),tipo:tipo||'Entrada',valor:n(valor),desc:desc||'',cat:cat||'Geral',forma:forma||''})};
window.caixa=function(){let b=$('p-caixa');if(!b)return;let m=arr('caixa').slice().reverse(),r=m.map(x=>`<tr><td>${br(x.data)}</td><td>${x.tipo}</td><td>${x.desc||'—'}</td><td>${x.forma||'—'}</td><td><b>${money(x.valor)}</b></td></tr>`).join('');let e=m.filter(x=>x.tipo==='Entrada').reduce((a,x)=>a+n(x.valor),0),s=m.filter(x=>x.tipo==='Saída'||x.tipo==='Saida').reduce((a,x)=>a+n(x.valor),0);b.innerHTML=`<div class="grid3"><div class="metric"><div class="label">Entradas</div><div class="value green">${money(e)}</div></div><div class="metric"><div class="label">Saídas</div><div class="value red">${money(s)}</div></div><div class="metric"><div class="label">Saldo</div><div class="value">${money(e-s)}</div></div></div><div class="card"><h3>Movimentações</h3><table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Forma</th><th>Valor</th></tr></thead><tbody>${r||'<tr><td colspan="5" class="empty">Nenhuma movimentação.</td></tr>'}</tbody></table></div>`};
function vd(v){return String(v.data||v.dataVenda||v.createdAt||'').slice(0,10)}function vi(v){return Array.isArray(v.itens)?v.itens:[]}function vc(v){return v.cliente||v.clienteNome||v.nomeCliente||'Cliente sem cadastro'}function vf(v){return v.forma||v.formaPagamento||v.pagamento||'—'}function vn(v){return v.num||v.numero||v.seq||'—'}
window.filtrarRelVendas=function(){let ei=document.getElementById('relIni'),ef=document.getElementById('relFim'),out=document.getElementById('relResultado');if(!ei||!ef||!out)return;let ini=ei.value,fim=ef.value;if(!ini||!fim){alert('Selecione a data inicial e final.');return}if(ini>fim){alert('A data inicial não pode ser maior que a data final.');return}let vs=arr('vendas').filter(v=>{let d=vd(v);return d>=ini&&d<=fim}).sort((a,b)=>vd(b).localeCompare(vd(a)));let total=vs.reduce((a,v)=>a+n(v.total),0),desc=vs.reduce((a,v)=>a+n(v.desc||v.desconto),0),ticket=vs.length?total/vs.length:0,qtd=0;vs.forEach(v=>vi(v).forEach(i=>qtd+=n(i.qtd||1)));let formas={};vs.forEach(v=>formas[vf(v)]=(formas[vf(v)]||0)+n(v.total));let fr=Object.entries(formas).map(([f,x])=>`<tr><td>${f}</td><td><b>${money(x)}</b></td></tr>`).join('');let rows=vs.map(v=>`<tr><td>${br(vd(v))}</td><td>#${vn(v)}</td><td>${vc(v)}</td><td>${vi(v).map(i=>`${n(i.qtd||1)}x ${i.nome||i.desc||i.produto||'Item'}`).join('<br>')||'—'}</td><td>${vf(v)}</td><td>${money(v.desc||v.desconto)}</td><td><b>${money(v.total)}</b></td></tr>`).join('');out.innerHTML=`<div class="grid4"><div class="metric"><div class="label">Vendas no período</div><div class="value blue">${vs.length}</div></div><div class="metric"><div class="label">Faturamento</div><div class="value green">${money(total)}</div></div><div class="metric"><div class="label">Ticket médio</div><div class="value gold">${money(ticket)}</div></div><div class="metric"><div class="label">Itens vendidos</div><div class="value">${qtd}</div></div></div><div class="grid2"><div class="card"><h3>Resumo</h3><p><b>Período:</b> ${br(ini)} até ${br(fim)}</p><p><b>Descontos concedidos:</b> ${money(desc)}</p><p><b>Total faturado:</b> ${money(total)}</p></div><div class="card"><h3>Por forma de pagamento</h3><table class="table"><tbody>${fr||'<tr><td>Sem vendas.</td></tr>'}</tbody></table></div></div><div class="card"><div class="head"><h3>Vendas detalhadas</h3><button class="btn sm" id="btnExportRel">Exportar CSV</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Data</th><th>Venda</th><th>Cliente</th><th>Produtos / Serviços</th><th>Pagamento</th><th>Desconto</th><th>Total</th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">Nenhuma venda encontrada neste período.</td></tr>'}</tbody></table></div></div>`;window.__relVendas=vs;let be=document.getElementById('btnExportRel');if(be)be.addEventListener('click',window.exportRelVendas)};
window.exportRelVendas=function(){let rows=[['Data','Venda','Cliente','Itens','Pagamento','Desconto','Total']];(window.__relVendas||[]).forEach(v=>rows.push([br(vd(v)),vn(v),vc(v),vi(v).map(i=>n(i.qtd||1)+'x '+(i.nome||i.desc||i.produto||'Item')).join(' | '),vf(v),n(v.desc||v.desconto).toFixed(2),n(v.total).toFixed(2)]));csvDownload('relatorio-vendas.csv',rows)};
window.relatorios=function(){let b=document.getElementById('p-relatorios');if(!b)return;let pi=today().slice(0,8)+'01';b.innerHTML=`<div class="card"><div class="head"><div><h3>Relatório detalhado de vendas</h3><div style="color:var(--mut);margin-top:4px">Selecione o período que deseja analisar.</div></div></div><div class="grid3"><div class="field"><label>Data inicial</label><input id="relIni" type="date" value="${pi}"></div><div class="field"><label>Data final</label><input id="relFim" type="date" value="${today()}"></div><div class="field"><label>&nbsp;</label><button id="btnGerarRel" type="button" class="btn goldbtn" style="width:100%">Gerar relatório</button></div></div></div><div id="relResultado"></div>`;let btn=document.getElementById('btnGerarRel');if(btn)btn.addEventListener('click',function(e){e.preventDefault();window.filtrarRelVendas()});setTimeout(()=>window.filtrarRelVendas(),0)};
try{if(typeof current!=='undefined'&&current==='relatorios')window.relatorios()}catch(e){console.error(e)}
})();