/* May Bike ERP V15.6 - camada de estabilizacao
   Mantem compatibilidade com os dados atuais e adiciona backup/restauracao, fechamento diario, organizacao alfabetica e CRM de revisoes. */
(function(){'use strict';
function A(k){if(!Array.isArray(st[k]))st[k]=[];return st[k]}
function N(v){return Number(v||0)}
function E(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function alpha(a,b,campo){return String((a&&a[campo])||'').localeCompare(String((b&&b[campo])||''),'pt-BR',{sensitivity:'base',numeric:true})}
window.ordenarCadastrosAlfabetico=function(){A('clientes').sort((a,b)=>alpha(a,b,'nome'));A('maoObra').sort((a,b)=>alpha(a,b,'nome'));A('estoque').sort((a,b)=>alpha(a,b,'desc'))};
window.ordenarCadastrosAlfabetico();
var saveBase=window.save;if(typeof saveBase==='function'){window.save=async function(){window.ordenarCadastrosAlfabetico();return saveBase.apply(this,arguments)}}
window.mbToast=function(msg){var x=document.getElementById('mb-toast');if(!x){x=document.createElement('div');x.id='mb-toast';x.style.cssText='position:fixed;right:22px;bottom:22px;z-index:99999;background:#17202d;border:1px solid #f0b719;color:#fff;padding:14px 18px;border-radius:12px;box-shadow:0 12px 35px #0008;font-weight:700;max-width:360px';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';clearTimeout(window.__mbToastTimer);window.__mbToastTimer=setTimeout(()=>x.style.display='none',2600)};
window.exportarBackupCompleto=function(){try{window.ordenarCadastrosAlfabetico();var payload={produto:'May Bike ERP',versao:'15.6',geradoEm:new Date().toISOString(),state:JSON.parse(JSON.stringify(st))};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='maybike-backup-'+today()+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);if(typeof logAudit==='function')logAudit('Backup exportado','Backup completo do sistema');mbToast('Backup exportado com sucesso.')}catch(e){console.error(e);alert('Nao foi possivel gerar o backup.')}};
window.selecionarBackupRestaurar=function(){var i=document.getElementById('mb_backup_file');if(i)i.click()};
window.restaurarBackupArquivo=function(input){var file=input&&input.files&&input.files[0];if(!file)return;var r=new FileReader();r.onload=function(){try{var data=JSON.parse(r.result),novo=data&&data.state?data.state:data;if(!novo||typeof novo!=='object'||!Array.isArray(novo.vendas)||!Array.isArray(novo.clientes))throw new Error('Formato invalido');if(!confirm('ATENCAO: restaurar este backup substituirá os dados atuais do sistema. Deseja continuar?')){input.value='';return}try{localStorage.setItem('maybike_backup_antes_restauracao_'+Date.now(),JSON.stringify(st))}catch(e){};Object.keys(st).forEach(k=>delete st[k]);Object.assign(st,novo);if(typeof migrateV13==='function')migrateV13();window.ordenarCadastrosAlfabetico();if(typeof logAudit==='function')logAudit('Backup restaurado','Restauracao manual de backup');Promise.resolve(save()).then(()=>{mbToast('Backup restaurado com sucesso.');setTimeout(()=>location.reload(),700)});input.value=''}catch(e){console.error(e);alert('Arquivo de backup invalido ou corrompido.');input.value=''}};r.readAsText(file)};
function movimentosDia(data){return A('caixa').filter(x=>String(x.data||'').slice(0,10)===data)}
function resumoDia(data){var m=movimentosDia(data),ent=m.filter(x=>x.tipo==='Entrada').reduce((a,x)=>a+N(x.valor),0),sai=m.filter(x=>x.tipo==='Saída'||x.tipo==='Saida').reduce((a,x)=>a+N(x.valor),0);return {m,ent,sai,saldo:ent-sai}}
window.fecharCaixaDia=function(){var data=(document.getElementById('fc_data')||{}).value||today(),r=resumoDia(data),inf=N((document.getElementById('fc_saldo')||{}).value),obs=(document.getElementById('fc_obs')||{}).value||'';var f=A('fechamentos');if(f.some(x=>x.data===data))return alert('O caixa desta data ja foi fechado.');if(!confirm('Confirmar fechamento do caixa de '+br(data)+'?'))return;var obj={id:uid(),data:data,dataHora:new Date().toISOString(),entradas:r.ent,saidas:r.sai,saldoSistema:r.saldo,saldoInformado:inf,diferenca:inf-r.saldo,obs:obs,usuario:(function(){try{return JSON.parse(sessionStorage.mbUser||'{}').nome||'Administrador'}catch(e){return 'Administrador'}})()};f.push(obj);if(typeof logAudit==='function')logAudit('Caixa fechado',br(data)+' / saldo '+money(r.saldo)+' / diferenca '+money(obj.diferenca));save();mbToast('Caixa fechado com sucesso.');setTimeout(()=>{if(typeof caixa==='function')caixa()},200)};
window.excluirFechamentoCaixa=function(id){if(!confirm('Reabrir este fechamento de caixa?'))return;st.fechamentos=A('fechamentos').filter(x=>x.id!==id);if(typeof logAudit==='function')logAudit('Caixa reaberto',id);save();setTimeout(()=>{if(typeof caixa==='function')caixa()},150)};
function blocoFechamento(){var data=today(),r=resumoDia(data),f=A('fechamentos').slice().sort((a,b)=>(b.data||'').localeCompare(a.data||''));var rows=f.map(x=>`<tr><td>${br(x.data)}</td><td>${money(x.entradas)}</td><td>${money(x.saidas)}</td><td><b>${money(x.saldoSistema)}</b></td><td>${money(x.saldoInformado)}</td><td class="${Math.abs(N(x.diferenca))<0.01?'green':'red'}">${money(x.diferenca)}</td><td>${E(x.usuario||'—')}</td><td><button class="btn sm" onclick="excluirFechamentoCaixa('${x.id}')">Reabrir</button></td></tr>`).join('');return `<div class="card" style="margin-top:16px"><div class="head"><div><h3>Fechamento diário de caixa</h3><div style="color:var(--mut);margin-top:4px">Confira o saldo do sistema e informe o valor realmente contado.</div></div></div><div class="form3"><div class="field"><label>Data</label><input id="fc_data" type="date" value="${data}" onchange="if(typeof caixa==='function')caixa()"></div><div class="field"><label>Saldo contado / conferido</label><input id="fc_saldo" type="number" step="0.01" value="${r.saldo.toFixed(2)}"></div><div class="field"><label>Observação</label><input id="fc_obs" placeholder="Ex.: diferença de troco, sangria..."></div></div><div class="grid3" style="margin-top:12px"><div class="metric"><div class="label">Entradas do dia</div><div class="value green">${money(r.ent)}</div></div><div class="metric"><div class="label">Saídas do dia</div><div class="value red">${money(r.sai)}</div></div><div class="metric"><div class="label">Saldo do sistema</div><div class="value gold">${money(r.saldo)}</div></div></div><div class="actions"><button class="btn goldbtn" onclick="fecharCaixaDia()">Fechar caixa do dia</button></div><div style="overflow:auto;margin-top:18px"><table class="table"><thead><tr><th>Data</th><th>Entradas</th><th>Saídas</th><th>Saldo sistema</th><th>Saldo contado</th><th>Diferença</th><th>Usuário</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty">Nenhum fechamento realizado.</td></tr>'}</tbody></table></div></div>`}
var caixaBase=window.caixa;if(typeof caixaBase==='function'){window.caixa=function(){var ret=caixaBase.apply(this,arguments),b=document.getElementById('p-caixa');if(b&&!document.getElementById('fc_data'))b.insertAdjacentHTML('beforeend',blocoFechamento());return ret}};
var configBase=window.config;if(typeof configBase==='function'){window.config=function(){var ret=configBase.apply(this,arguments),b=document.getElementById('p-config');if(b&&!document.getElementById('mb_backup_file'))b.insertAdjacentHTML('beforeend',`<div class="card" style="margin-top:16px"><div class="head"><div><h3>Segurança e backup — V15.6</h3><div style="color:var(--mut);margin-top:4px">Faça backup antes de atualizações importantes. A restauração substitui os dados atuais.</div></div><span class="pill">V15.6 Estável</span></div><div class="actions"><button class="btn goldbtn" onclick="exportarBackupCompleto()">Exportar backup completo</button><button class="btn" onclick="selecionarBackupRestaurar()">Restaurar backup</button><input id="mb_backup_file" type="file" accept="application/json,.json" style="display:none" onchange="restaurarBackupArquivo(this)"></div></div>`);return ret}};

/* CRM REVISOES */
function addDias(data,dias){if(!data)return'';var d=new Date(String(data).slice(0,10)+'T12:00:00');d.setDate(d.getDate()+Number(dias||0));return d.toISOString().slice(0,10)}
function diasAte(data){if(!data)return 99999;var a=new Date(today()+'T12:00:00'),b=new Date(data+'T12:00:00');return Math.round((b-a)/86400000)}
function clientePorNome(nome){return A('clientes').find(c=>String(c.nome||'').toLocaleLowerCase('pt-BR')===String(nome||'').toLocaleLowerCase('pt-BR'))||{}}
function crmRegistros(){var dias=N((st.config||{}).revisaoDias||120),map={};function add(ref){if(!ref.cliente||!ref.dataBase)return;var dataRev=ref.dataRevisao||addDias(ref.dataBase,dias),key=(ref.cliente+'|'+(ref.bike||'')+'|'+dataRev).toLocaleLowerCase('pt-BR');if(!map[key]||String(ref.dataBase)>String(map[key].dataBase))map[key]={...ref,dataRevisao:dataRev}}
A('os').filter(o=>o.status!=='Cancelada').forEach(o=>add({id:'os-'+o.id,origem:'OS #'+(o.num||'—'),cliente:o.cliente,bike:o.bike||'Bicicleta',dataBase:o.data,dataRevisao:o.revisaoEm||o.proximaRevisao}));
A('vendas').forEach(v=>{var bike=(v.bikeVenda&&[v.bikeVenda.marca,v.bikeVenda.modelo].filter(Boolean).join(' '))||v.bike||'';if(bike)add({id:'v-'+v.id,origem:'Venda #'+(v.num||'—'),cliente:v.cliente,bike:bike,dataBase:v.data,dataRevisao:v.proximaRevisao})});
return Object.values(map).map(r=>{var c=clientePorNome(r.cliente),cont=A('crmContatos').find(x=>x.refId===r.id)||{};return {...r,whats:c.whats||c.whatsapp||'',contato:cont}}).sort((a,b)=>(a.dataRevisao||'').localeCompare(b.dataRevisao||''))}
window.marcarContatoCRM=function(refId){var regs=crmRegistros(),r=regs.find(x=>x.id===refId);if(!r)return;var a=A('crmContatos'),i=a.findIndex(x=>x.refId===refId),obj={id:i>=0?a[i].id:uid(),refId:refId,data:today(),dataHora:new Date().toISOString(),cliente:r.cliente,status:'Contatado'};if(i>=0)a[i]=obj;else a.push(obj);if(typeof logAudit==='function')logAudit('CRM revisão contatado',r.cliente+' / '+r.dataRevisao);save();mbToast('Contato registrado no CRM.');setTimeout(()=>window.crmPage(),120)};
window.abrirWhatsCRM=function(refId){var r=crmRegistros().find(x=>x.id===refId);if(!r)return;if(!r.whats)return alert('Este cliente não possui WhatsApp cadastrado.');var msg='Olá, '+r.cliente+'! Aqui é da May Bike. Passando para lembrar que está chegando o período recomendado para revisão da sua '+(r.bike||'bicicleta')+'. Podemos agendar um horário para você?';var url=typeof whatsappUrl==='function'?whatsappUrl(msg,r.whats):('https://wa.me/'+String(r.whats).replace(/\D/g,'')+'?text='+encodeURIComponent(msg));window.open(url,'_blank')};
window.crmPage=function(){var b=document.getElementById('p-crm');if(!b)return;var regs=crmRegistros(),hoje=today(),venc=regs.filter(r=>r.dataRevisao<hoje&&!r.contato.data).length,proximas=regs.filter(r=>{var d=diasAte(r.dataRevisao);return d>=0&&d<=30&&!r.contato.data}).length,cont=regs.filter(r=>r.contato.data).length;var filtro=(document.getElementById('crmFiltro')||{}).value||'todos';var lista=regs.filter(r=>filtro==='todos'||(filtro==='atrasados'&&r.dataRevisao<hoje&&!r.contato.data)||(filtro==='30dias'&&diasAte(r.dataRevisao)>=0&&diasAte(r.dataRevisao)<=30&&!r.contato.data)||(filtro==='contatados'&&r.contato.data));var rows=lista.map(r=>{var d=diasAte(r.dataRevisao),status=r.contato.data?'<span class="badge b3">Contatado</span>':d<0?'<span class="badge b5">Atrasado '+Math.abs(d)+' dia(s)</span>':d===0?'<span class="badge b2">Revisão hoje</span>':d<=30?'<span class="badge b2">Em '+d+' dia(s)</span>':'<span class="badge b1">Programado</span>';return `<tr><td><b>${E(r.cliente)}</b><br><small>${E(r.whats||'Sem WhatsApp')}</small></td><td>${E(r.bike||'—')}</td><td>${E(r.origem)}</td><td>${br(r.dataRevisao)}</td><td>${status}</td><td>${r.contato.data?'<small>Contato em '+br(r.contato.data)+'</small>':`<button class="btn sm" onclick="abrirWhatsCRM('${r.id}')">WhatsApp</button> <button class="btn goldbtn sm" onclick="marcarContatoCRM('${r.id}')">Marcar contato</button>`}</td></tr>`}).join('');b.innerHTML=`<div class="grid3"><div class="metric"><div class="label">Revisões atrasadas</div><div class="value red">${venc}</div></div><div class="metric"><div class="label">Próximos 30 dias</div><div class="value gold">${proximas}</div></div><div class="metric"><div class="label">Clientes contatados</div><div class="value green">${cont}</div></div></div><div class="card"><div class="head"><div><h3>CRM de Revisões</h3><div style="color:var(--mut);margin-top:4px">Retornos calculados automaticamente em ${(st.config||{}).revisaoDias||120} dias após venda/OS.</div></div><select id="crmFiltro" onchange="crmPage()"><option value="todos">Todos</option><option value="atrasados">Atrasados</option><option value="30dias">Próximos 30 dias</option><option value="contatados">Contatados</option></select></div><div style="overflow:auto"><table class="table"><thead><tr><th>Cliente</th><th>Bicicleta</th><th>Origem</th><th>Próxima revisão</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="empty">Nenhuma revisão programada. As revisões aparecem automaticamente a partir das vendas e ordens de serviço com bicicleta/cliente.</td></tr>'}</tbody></table></div></div>`;var f=document.getElementById('crmFiltro');if(f)f.value=filtro};

var renderBase=window.render;if(typeof renderBase==='function'){window.render=function(p){if(p==='clientes'||p==='maoobra'||p==='estoque')window.ordenarCadastrosAlfabetico();if(p==='crm')return window.crmPage();return renderBase.apply(this,arguments)}};
A('fechamentos');A('crmContatos');st.config=st.config||{};st.config.versaoSistema='15.6';
})();