/* May Bike ERP V16.1 - Venda com cliente, dados da bike e cancelamento */
(function(){'use strict';
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function listaClientes(){return (typeof st!=='undefined'&&Array.isArray(st.clientes)?st.clientes:[]).slice().sort((a,b)=>String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base',numeric:true}))}
function cliById(id){return listaClientes().find(c=>String(c.id)===String(id))}
window.v160FiltrarClientes=function(q){const box=document.getElementById('v160_cli_lista');if(!box)return;const t=String(q||'').trim().toLocaleLowerCase('pt-BR');const arr=listaClientes().filter(c=>!t||[c.nome,c.whats,c.whatsapp,c.cpf,c.email,c.end,c.endereco,c.cidade].some(v=>String(v||'').toLocaleLowerCase('pt-BR').includes(t)));box.innerHTML=arr.length?arr.slice(0,100).map(c=>`<button type="button" class="btn" style="display:block;width:100%;text-align:left;margin-bottom:6px;padding:10px 12px" onclick="v160SelecionarCliente('${esc(c.id)}')"><b>${esc(c.nome||'Sem nome')}</b><br><small>${esc(c.whats||c.whatsapp||'Sem WhatsApp')}${c.cpf?' • CPF '+esc(c.cpf):''}${c.email?' • '+esc(c.email):''}</small></button>`).join(''):`<div class="notice">Nenhum cliente encontrado. Clientes cadastrados: ${listaClientes().length}</div>`};
window.v160AbrirBuscaCliente=function(){const p=document.getElementById('v160_cli_painel');if(!p)return;p.style.display='block';const q=document.getElementById('v160_cli_q');if(q){q.value='';q.focus()}window.v160FiltrarClientes('')};
window.v160FecharBuscaCliente=function(){const p=document.getElementById('v160_cli_painel');if(p)p.style.display='none'};
window.v160SelecionarCliente=function(id){const c=cliById(id);if(!c)return;const inp=document.getElementById('vr_cli');if(inp)inp.value=c.nome||'';window.__mbVendaClienteId=c.id;const d=document.getElementById('v160_cli_detalhes');if(d){const end=[c.end||c.endereco,c.numero,c.bairro,c.cidade,c.uf].filter(Boolean).join(' • ');d.innerHTML=`<div class="notice" style="margin-top:8px"><b>${esc(c.nome||'Cliente')}</b>${c.whats||c.whatsapp?`<br>📱 ${esc(c.whats||c.whatsapp)}`:''}${c.cpf?`<br>CPF: ${esc(c.cpf)}`:''}${c.email?`<br>✉ ${esc(c.email)}`:''}${end?`<br>📍 ${esc(end)}`:''}</div>`;d.style.display='block'}window.v160FecharBuscaCliente()};
window.v161ToggleBike=function(){const b=document.getElementById('v161_bike_box'),ck=document.getElementById('v161_tem_bike');if(b)b.style.display=ck&&ck.checked?'block':'none'};
function bikeDraft(){const ck=document.getElementById('v161_tem_bike');if(!ck||!ck.checked)return null;return {marca:(document.getElementById('v161_bike_marca')?.value||'').trim(),modelo:(document.getElementById('v161_bike_modelo')?.value||'').trim(),quadro:(document.getElementById('v161_bike_quadro')?.value||'').trim(),cor:(document.getElementById('v161_bike_cor')?.value||'').trim(),aro:(document.getElementById('v161_bike_aro')?.value||'').trim(),tamanho:(document.getElementById('v161_bike_tam')?.value||'').trim(),ano:(document.getElementById('v161_bike_ano')?.value||'').trim(),obs:(document.getElementById('v161_bike_obs')?.value||'').trim()}}
window.v161FinalizarVenda=async function(){const bike=bikeDraft();if(bike&&!bike.quadro)return alert('Informe o número do quadro da bicicleta.');const before=(st.vendas||[]).length;const base=window.saveVendaRapida;if(typeof base!=='function')return alert('Função de venda indisponível.');await base();setTimeout(async()=>{try{if((st.vendas||[]).length<=before)return;const v=st.vendas[st.vendas.length-1];if(!v)return;if(bike){v.bicicleta={...bike};v.bike=bike.marca+' '+bike.modelo+(bike.quadro?' • Quadro '+bike.quadro:'');st.bikes=Array.isArray(st.bikes)?st.bikes:[];const existe=st.bikes.some(x=>bike.quadro&&String(x.quadro||'').toLowerCase()===bike.quadro.toLowerCase());if(!existe)st.bikes.push({id:uid(),cliente:v.cliente||'',clienteId:v.clienteId||window.__mbVendaClienteId||'',...bike,vendaId:v.id,dataCadastro:today()});if(typeof logAudit==='function')logAudit('Bicicleta vinculada à venda',(v.cod||('#'+v.num))+' / '+bike.marca+' '+bike.modelo+' / quadro '+bike.quadro);await save()}}catch(e){console.error('Erro ao salvar dados da bicicleta',e)}},250)};
function abrirVenda(){try{if(typeof modal!=='function'||typeof pecasHTML!=='function'||typeof payHTML!=='function'||typeof maoHTML!=='function')return alert('PDV indisponível: funções da venda não carregadas.');window.__mbVendaClienteId='';modal(`<div class="mhead"><h3>Nova venda — V16.1</h3><button class="btn" onclick="closeM()">Fechar</button></div>
<div class="field"><label>Cliente</label><div style="display:flex;gap:8px;align-items:center"><input id="vr_cli" value="Cliente sem cadastro" placeholder="Cliente sem cadastro" style="flex:1"><button type="button" class="btn goldbtn" onclick="v160AbrirBuscaCliente()" title="Buscar cliente cadastrado">🔍 Buscar cliente</button></div><div id="v160_cli_detalhes" style="display:none"></div><div id="v160_cli_painel" class="card" style="display:none;margin-top:8px"><div style="display:flex;gap:8px"><input id="v160_cli_q" placeholder="Digite nome, WhatsApp, CPF ou e-mail" oninput="v160FiltrarClientes(this.value)" style="flex:1"><button type="button" class="btn" onclick="v160FecharBuscaCliente()">Fechar</button></div><div id="v160_cli_lista" style="max-height:300px;overflow:auto;margin-top:10px"></div></div></div>
<div class="card"><h3>Produtos</h3>${pecasHTML([])}</div>
<div class="card"><h3>🚲 Dados da bicicleta</h3><label style="display:flex;gap:8px;align-items:center;cursor:pointer"><input id="v161_tem_bike" type="checkbox" onchange="v161ToggleBike()" style="width:auto"> Esta venda inclui uma bicicleta</label><div id="v161_bike_box" style="display:none;margin-top:12px"><div class="form3"><div class="field"><label>Marca</label><input id="v161_bike_marca" placeholder="Ex.: Oggi"></div><div class="field"><label>Modelo</label><input id="v161_bike_modelo" placeholder="Ex.: Hacker Sport"></div><div class="field"><label>Nº do quadro *</label><input id="v161_bike_quadro" placeholder="Número / serial do quadro"></div><div class="field"><label>Cor</label><input id="v161_bike_cor"></div><div class="field"><label>Aro</label><input id="v161_bike_aro" placeholder="29"></div><div class="field"><label>Tamanho do quadro</label><input id="v161_bike_tam" placeholder="M / 17 / 19..."></div><div class="field"><label>Ano</label><input id="v161_bike_ano"></div></div><div class="field"><label>Observações da bicicleta</label><textarea id="v161_bike_obs" placeholder="Detalhes, acessórios, características..."></textarea></div><div class="notice">Ao concluir a venda, a bicicleta será vinculada ao cliente e também ficará disponível na aba Bicicletas.</div></div></div>
<div class="card"><h3>🔧 Serviços / Mão de obra</h3>${maoHTML([])}<div class="notice" style="margin-top:10px">Selecione um serviço já cadastrado ou adicione um serviço manual. O valor será somado à venda.</div></div>
${payHTML(0)}
<div class="actions"><button class="btn goldbtn" onclick="v161FinalizarVenda()">Concluir venda</button></div>`);if(typeof payRecalc==='function')payRecalc()}catch(e){console.error(e);alert('Não foi possível abrir a Nova Venda: '+(e.message||e))}}
window.openVendaRapida=abrirVenda;
window.v161CancelarVenda=async function(id){const v=(st.vendas||[]).find(x=>String(x.id)===String(id));if(!v)return alert('Venda não encontrada.');if(String(v.status||'').toLowerCase()==='cancelada')return alert('Esta venda já está cancelada.');if(!confirm('Cancelar esta venda? O estoque dos produtos será devolvido e o movimento financeiro será estornado.'))return;v.status='Cancelada';v.canceladaEm=new Date().toISOString();v.canceladaPor=(JSON.parse(sessionStorage.mbUser||'{}').nome||'Sistema');if(!v.estoqueEstornado){(v.itens||[]).forEach(i=>{const p=(st.estoque||[]).find(x=>String(x.id)===String(i.prodId));if(p)p.qtd=Number(p.qtd||0)+Number(i.qtd||0)});v.estoqueEstornado=true}st.caixa=Array.isArray(st.caixa)?st.caixa:[];const ref=v.cod||('Venda #'+v.num);const ja=st.caixa.some(x=>x.estornoVendaId===v.id);if(!ja){const recebido=Number(v.entrada!=null?v.entrada:v.total||0);if(recebido>0)st.caixa.push({id:uid(),data:today(),tipo:'Saída',desc:'Estorno '+ref+' - '+(v.cliente||''),cat:'Cancelamento de venda',forma:v.forma||'',valor:recebido,estornoVendaId:v.id})}if(Array.isArray(st.contas))st.contas.forEach(c=>{if((c.vendaId&&String(c.vendaId)===String(v.id))||(c.desc||'').includes(ref)){if(c.status!=='Pago')c.status='Cancelada'}});if(typeof logAudit==='function')logAudit('Venda cancelada',ref+' / '+(v.cliente||'')+' / '+money(v.total));await save();go('vendas');alert('Venda cancelada com sucesso. Estoque e financeiro foram ajustados.')};
function adicionarBotoesCancelar(){const page=document.getElementById('p-vendas');if(!page)return;page.querySelectorAll('button').forEach(btn=>{if((btn.textContent||'').trim()!=='Recibo'||btn.dataset.cancelPatch)return;const oc=btn.getAttribute('onclick')||'';const m=oc.match(/printRec\(['\"]([^'\"]+)['\"]\)/);if(!m)return;const id=m[1],v=(st.vendas||[]).find(x=>String(x.id)===String(id));btn.dataset.cancelPatch='1';if(v&&String(v.status||'').toLowerCase()!=='cancelada'){const c=document.createElement('button');c.type='button';c.className='btn redbtn sm';c.textContent='Cancelar';c.style.marginLeft='6px';c.onclick=()=>window.v161CancelarVenda(id);btn.insertAdjacentElement('afterend',c)}else if(v){btn.disabled=true;btn.title='Venda cancelada'}})}
const obs=new MutationObserver(adicionarBotoesCancelar);obs.observe(document.documentElement,{subtree:true,childList:true});setInterval(adicionarBotoesCancelar,800);setTimeout(()=>{window.openVendaRapida=abrirVenda},0);setTimeout(()=>{window.openVendaRapida=abrirVenda},500);setTimeout(()=>{window.openVendaRapida=abrirVenda},1500);
})();