/* May Bike ERP V16.0 - Nova Venda estável com busca de cliente */
(function(){'use strict';
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function listaClientes(){return (typeof st!=='undefined'&&Array.isArray(st.clientes)?st.clientes:[]).slice().sort((a,b)=>String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base',numeric:true}))}
function cliById(id){return listaClientes().find(c=>String(c.id)===String(id))}
window.v160FiltrarClientes=function(q){const box=document.getElementById('v160_cli_lista');if(!box)return;const t=String(q||'').trim().toLocaleLowerCase('pt-BR');const arr=listaClientes().filter(c=>!t||[c.nome,c.whats,c.whatsapp,c.cpf,c.email,c.end,c.endereco,c.cidade].some(v=>String(v||'').toLocaleLowerCase('pt-BR').includes(t)));box.innerHTML=arr.length?arr.slice(0,100).map(c=>`<button type="button" class="btn" style="display:block;width:100%;text-align:left;margin-bottom:6px;padding:10px 12px" onclick="v160SelecionarCliente('${esc(c.id)}')"><b>${esc(c.nome||'Sem nome')}</b><br><small>${esc(c.whats||c.whatsapp||'Sem WhatsApp')}${c.cpf?' • CPF '+esc(c.cpf):''}${c.email?' • '+esc(c.email):''}</small></button>`).join(''):`<div class="notice">Nenhum cliente encontrado. Clientes cadastrados: ${listaClientes().length}</div>`};
window.v160AbrirBuscaCliente=function(){const p=document.getElementById('v160_cli_painel');if(!p)return;p.style.display='block';const q=document.getElementById('v160_cli_q');if(q){q.value='';q.focus()}window.v160FiltrarClientes('')};
window.v160FecharBuscaCliente=function(){const p=document.getElementById('v160_cli_painel');if(p)p.style.display='none'};
window.v160SelecionarCliente=function(id){const c=cliById(id);if(!c)return;const inp=document.getElementById('vr_cli');if(inp)inp.value=c.nome||'';window.__mbVendaClienteId=c.id;const d=document.getElementById('v160_cli_detalhes');if(d){const end=[c.end||c.endereco,c.numero,c.bairro,c.cidade,c.uf].filter(Boolean).join(' • ');d.innerHTML=`<div class="notice" style="margin-top:8px"><b>${esc(c.nome||'Cliente')}</b>${c.whats||c.whatsapp?`<br>📱 ${esc(c.whats||c.whatsapp)}`:''}${c.cpf?`<br>CPF: ${esc(c.cpf)}`:''}${c.email?`<br>✉ ${esc(c.email)}`:''}${end?`<br>📍 ${esc(end)}`:''}</div>`;d.style.display='block'}window.v160FecharBuscaCliente()};
function abrirVenda(){try{if(typeof modal!=='function'||typeof pecasHTML!=='function'||typeof payHTML!=='function'||typeof maoHTML!=='function')return alert('PDV indisponível: funções da venda não carregadas.');window.__mbVendaClienteId='';modal(`<div class="mhead"><h3>Nova venda — V16</h3><button class="btn" onclick="closeM()">Fechar</button></div>
<div class="field"><label>Cliente</label><div style="display:flex;gap:8px;align-items:center"><input id="vr_cli" value="Cliente sem cadastro" placeholder="Cliente sem cadastro" style="flex:1"><button type="button" class="btn goldbtn" onclick="v160AbrirBuscaCliente()" title="Buscar cliente cadastrado">🔍 Buscar cliente</button></div><div id="v160_cli_detalhes" style="display:none"></div><div id="v160_cli_painel" class="card" style="display:none;margin-top:8px"><div style="display:flex;gap:8px"><input id="v160_cli_q" placeholder="Digite nome, WhatsApp, CPF ou e-mail" oninput="v160FiltrarClientes(this.value)" style="flex:1"><button type="button" class="btn" onclick="v160FecharBuscaCliente()">Fechar</button></div><div id="v160_cli_lista" style="max-height:300px;overflow:auto;margin-top:10px"></div></div></div>
<div class="card"><h3>Produtos</h3>${pecasHTML([])}</div>
<div class="card"><h3>🔧 Serviços / Mão de obra</h3>${maoHTML([])}<div class="notice" style="margin-top:10px">Selecione um serviço já cadastrado ou adicione um serviço manual. O valor será somado à venda.</div></div>
${payHTML(0)}
<div class="actions"><button class="btn goldbtn" onclick="saveVendaRapida()">Finalizar venda</button></div>`);if(typeof payRecalc==='function')payRecalc()}catch(e){console.error(e);alert('Não foi possível abrir a Nova Venda: '+(e.message||e))}}
window.openVendaRapida=abrirVenda;
/* reforço contra scripts antigos que tentem substituir depois */
setTimeout(()=>{window.openVendaRapida=abrirVenda},0);setTimeout(()=>{window.openVendaRapida=abrirVenda},500);setTimeout(()=>{window.openVendaRapida=abrirVenda},1500);
})();