/* May Bike ERP V17.0 - Gestao, historicos, financeiro, estoque, backup e diagnostico */
(function(){'use strict';
const A=k=>{if(!Array.isArray(st[k]))st[k]=[];return st[k]};
const N=v=>Number(v||0);
const E=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const usuario=()=>{try{return JSON.parse(sessionStorage.mbUser||'{}').nome||'Sistema'}catch(e){return'Sistema'}};
const fechado=data=>A('fechamentos').some(f=>String(f.data)===String(data));
A('movEstoque');A('baixasReceber');A('fechamentos');A('audit');

/* ===== BACKUP AUTOMATICO LOCAL ===== */
function autoBackup(){try{const key='maybike_auto_backups_v17',agora=Date.now(),ultimo=N(localStorage.getItem('maybike_auto_backup_last'));if(agora-ultimo<30*60*1000)return;let lista=JSON.parse(localStorage.getItem(key)||'[]');lista.unshift({data:new Date().toISOString(),state:JSON.parse(JSON.stringify(st))});lista=lista.slice(0,8);localStorage.setItem(key,JSON.stringify(lista));localStorage.setItem('maybike_auto_backup_last',String(agora))}catch(e){console.warn('Backup automatico',e)}}
window.v170BaixarUltimoAutoBackup=function(){try{let lista=JSON.parse(localStorage.getItem('maybike_auto_backups_v17')||'[]');if(!lista.length)return alert('Ainda não existe backup automático neste navegador.');let blob=new Blob([JSON.stringify({produto:'May Bike ERP',versao:'17.0',tipo:'backup automatico',...lista[0]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='maybike-auto-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert('Não foi possível baixar o backup automático.')}};

/* ===== HISTORICO DE ESTOQUE POR DIFERENCA ===== */
let snap={};function snapshot(){snap={};A('estoque').forEach(p=>snap[p.id]=N(p.qtd))}snapshot();
function registrarMovEstoque(){const agora={};A('estoque').forEach(p=>{agora[p.id]=N(p.qtd);if(Object.prototype.hasOwnProperty.call(snap,p.id)){const dif=agora[p.id]-N(snap[p.id]);if(Math.abs(dif)>0.000001)A('movEstoque').push({id:uid(),data:today(),dataHora:new Date().toISOString(),produtoId:p.id,produto:p.desc||p.nome||'Produto',tipo:dif>0?'Entrada / ajuste':'Saída / ajuste',quantidade:Math.abs(dif),saldoAnterior:N(snap[p.id]),saldoNovo:agora[p.id],usuario:usuario()})}});snap=agora}
const save0=window.save;if(typeof save0==='function'){window.save=async function(){registrarMovEstoque();autoBackup();return save0.apply(this,arguments)}};

/* Snapshot de custo nas novas vendas para lucro historico mais confiavel */
const sv0=window.saveVendaRapida;if(typeof sv0==='function'){window.saveVendaRapida=async function(){const antes=A('vendas').length,r=await sv0.apply(this,arguments);if(A('vendas').length>antes){const v=A('vendas')[A('vendas').length-1];(v.itens||[]).forEach(i=>{const p=A('estoque').find(x=>String(x.id)===String(i.prodId));if(i.custoUnitario==null)i.custoUnitario=p?N(p.custoReal||p.custo||p.precoCompra):0});v.custoTotal=(v.itens||[]).reduce((a,i)=>a+N(i.qtd||1)*N(i.custoUnitario),0)}return r}};
function custoVenda(v){return (v.itens||[]).reduce((a,i)=>{let c=i.custoUnitario;if(c==null){let p=A('estoque').find(x=>String(x.id)===String(i.prodId));c=p?N(p.custoReal||p.custo||p.precoCompra):0}return a+N(i.qtd||1)*N(c)},0)}
function vendaValida(v){return String(v.status||'').toLowerCase()!=='cancelada'}

/* ===== HISTORICO DO CLIENTE ===== */
window.v170HistoricoCliente=function(id){const c=A('clientes').find(x=>String(x.id)===String(id));if(!c)return alert('Cliente não encontrado.');const nome=String(c.nome||'');const vendas=A('vendas').filter(v=>String(v.clienteId||'')===String(id)||String(v.cliente||'').toLowerCase()===nome.toLowerCase()).sort((a,b)=>(b.data||'').localeCompare(a.data||''));const oss=A('os').filter(o=>String(o.clienteId||'')===String(id)||String(o.cliente||'').toLowerCase()===nome.toLowerCase()).sort((a,b)=>(b.data||'').localeCompare(a.data||''));const bikes=A('bikes').filter(b=>String(b.clienteId||'')===String(id)||String(b.cliente||'').toLowerCase()===nome.toLowerCase());const total=vendas.filter(vendaValida).reduce((a,v)=>a+N(v.total),0);const vr=vendas.slice(0,20).map(v=>`<tr><td>${br(v.data)}</td><td>#${E(v.num||'—')}</td><td>${E(v.forma||'—')}</td><td>${money(v.total)}</td><td>${E(v.status||'Recebida')}</td></tr>`).join('');const or=oss.slice(0,20).map(o=>`<tr><td>${br(o.data)}</td><td>#${E(o.num||'—')}</td><td>${E(o.bike||'—')}</td><td>${money(typeof calcOS==='function'?calcOS(o).total:0)}</td><td>${E(o.status||'—')}</td></tr>`).join('');const brs=bikes.map(b=>`<tr><td><b>${E([b.marca,b.modelo].filter(Boolean).join(' ')||'Bicicleta')}</b></td><td>${E(b.quadro||'—')}</td><td>${E(b.cor||'—')}</td><td>${E(b.aro||'—')}</td></tr>`).join('');modal(`<div class="mhead"><h3>Histórico do cliente — ${E(nome)}</h3><button class="btn" onclick="closeM()">Fechar</button></div><div class="grid3"><div class="metric"><div class="label">Compras</div><div class="value blue">${vendas.length}</div></div><div class="metric"><div class="label">OS</div><div class="value gold">${oss.length}</div></div><div class="metric"><div class="label">Total gasto</div><div class="value green">${money(total)}</div></div></div><div class="card"><h3>🚲 Bicicletas</h3><table class="table"><thead><tr><th>Bike</th><th>Quadro</th><th>Cor</th><th>Aro</th></tr></thead><tbody>${brs||'<tr><td colspan="4" class="empty">Nenhuma bicicleta vinculada.</td></tr>'}</tbody></table></div><div class="card"><h3>🛒 Compras</h3><table class="table"><thead><tr><th>Data</th><th>Venda</th><th>Pagamento</th><th>Total</th><th>Status</th></tr></thead><tbody>${vr||'<tr><td colspan="5" class="empty">Nenhuma compra.</td></tr>'}</tbody></table></div><div class="card"><h3>🔧 Ordens de serviço</h3><table class="table"><thead><tr><th>Data</th><th>OS</th><th>Bike</th><th>Total</th><th>Status</th></tr></thead><tbody>${or||'<tr><td colspan="5" class="empty">Nenhuma OS.</td></tr>'}</tbody></table></div>`)};

/* ===== HISTORICO DA BIKE ===== */
window.v170HistoricoBike=function(id){const b=A('bikes').find(x=>String(x.id)===String(id));if(!b)return alert('Bicicleta não encontrada.');const chave=String(b.quadro||'').toLowerCase(),nome=[b.marca,b.modelo].filter(Boolean).join(' ');const oss=A('os').filter(o=>(chave&&String(o.quadro||o.bikeQuadro||'').toLowerCase()===chave)||String(o.bike||'').toLowerCase().includes(nome.toLowerCase())).sort((a,z)=>(z.data||'').localeCompare(a.data||''));const rows=oss.map(o=>`<tr><td>${br(o.data)}</td><td>#${E(o.num||'—')}</td><td>${E((o.mao||[]).map(x=>x.desc||x.nome).filter(Boolean).join(', ')||'Serviço')}</td><td>${money(typeof calcOS==='function'?calcOS(o).total:0)}</td><td>${E(o.status||'—')}</td></tr>`).join('');modal(`<div class="mhead"><h3>Histórico da bicicleta</h3><button class="btn" onclick="closeM()">Fechar</button></div><div class="card"><h3>${E(nome||'Bicicleta')}</h3><div class="notice"><b>Cliente:</b> ${E(b.cliente||'—')} &nbsp; • &nbsp; <b>Quadro:</b> ${E(b.quadro||'—')} &nbsp; • &nbsp; <b>Cor:</b> ${E(b.cor||'—')} &nbsp; • &nbsp; <b>Aro:</b> ${E(b.aro||'—')}</div></div><div class="card"><h3>Serviços realizados</h3><table class="table"><thead><tr><th>Data</th><th>OS</th><th>Serviço</th><th>Total</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">Nenhum serviço encontrado para esta bicicleta.</td></tr>'}</tbody></table></div>`)};

function injetarHistoricos(){const pc=document.getElementById('p-clientes');if(pc)pc.querySelectorAll('button[onclick*="openCliente"]').forEach(b=>{if(b.dataset.hist)return;b.dataset.hist='1';const m=(b.getAttribute('onclick')||'').match(/openCliente\(['\"]([^'\"]+)/);if(m){const h=document.createElement('button');h.className='btn sm';h.textContent='Histórico';h.style.marginLeft='6px';h.onclick=()=>v170HistoricoCliente(m[1]);b.insertAdjacentElement('afterend',h)}});const pb=document.getElementById('p-bicicletas');if(pb)pb.querySelectorAll('button[onclick*="openBike"]').forEach(b=>{if(b.dataset.hist)return;b.dataset.hist='1';const m=(b.getAttribute('onclick')||'').match(/openBike\(['\"]([^'\"]+)/);if(m){const h=document.createElement('button');h.className='btn sm';h.textContent='Histórico';h.style.marginLeft='6px';h.onclick=()=>v170HistoricoBike(m[1]);b.insertAdjacentElement('afterend',h)}})}
new MutationObserver(()=>setTimeout(injetarHistoricos,0)).observe(document.documentElement,{subtree:true,childList:true});setInterval(injetarHistoricos,1000);

/* ===== CONTAS A RECEBER / BAIXAS ===== */
window.v170BaixarConta=function(id){const c=A('contas').find(x=>String(x.id)===String(id));if(!c)return alert('Conta não encontrada.');if(String(c.status).toLowerCase()==='pago')return alert('Esta conta já está paga.');const saldo=Math.max(0,N(c.valorOriginal||c.valor)-N(c.valorPago));const val=N(prompt('Valor recebido (saldo atual '+money(saldo)+'):',saldo.toFixed(2)));if(!val||val<=0)return;const forma=prompt('Forma de recebimento: Dinheiro, PIX, Débito, Crédito, Transferência','PIX')||'PIX';c.valorPago=N(c.valorPago)+Math.min(val,saldo);c.saldo=Math.max(0,N(c.valorOriginal||c.valor)-c.valorPago);c.status=c.saldo<=0.009?'Pago':'Parcial';c.dataBaixa=today();A('baixasReceber').push({id:uid(),contaId:c.id,data:today(),valor:Math.min(val,saldo),forma,cliente:c.cliente||'',desc:c.desc||'',usuario:usuario()});A('caixa').push({id:uid(),data:today(),tipo:'Entrada',valor:Math.min(val,saldo),desc:'Recebimento '+(c.desc||c.cliente||'conta'),cat:'Contas a receber',forma,contaId:c.id});if(typeof logAudit==='function')logAudit('Conta recebida',(c.desc||c.cliente||c.id)+' / '+money(Math.min(val,saldo))+' / '+forma);save();setTimeout(()=>{if(typeof contas==='function')contas()},100)};
function blocoReceber(){const cs=A('contas').filter(c=>c.tipo==='A Receber'&&String(c.status||'').toLowerCase()!=='cancelada').slice().sort((a,b)=>(a.venc||'').localeCompare(b.venc||''));const aberto=cs.filter(c=>String(c.status).toLowerCase()!=='pago').reduce((a,c)=>a+Math.max(0,N(c.valorOriginal||c.valor)-N(c.valorPago)),0);const venc=cs.filter(c=>String(c.status).toLowerCase()!=='pago'&&c.venc&&c.venc<today()).reduce((a,c)=>a+Math.max(0,N(c.valorOriginal||c.valor)-N(c.valorPago)),0);const rows=cs.slice(0,80).map(c=>{const saldo=Math.max(0,N(c.valorOriginal||c.valor)-N(c.valorPago));return `<tr><td>${br(c.venc)}</td><td>${E(c.cliente||c.desc||'—')}</td><td>${money(c.valorOriginal||c.valor)}</td><td>${money(c.valorPago)}</td><td><b>${money(saldo)}</b></td><td>${E(c.status||'Aberto')}</td><td>${saldo>0?`<button class="btn goldbtn sm" onclick="v170BaixarConta('${c.id}')">Dar baixa</button>`:'—'}</td></tr>`}).join('');return `<div class="card" id="v170-receber"><div class="head"><div><h3>💳 Contas a receber — V17</h3><div style="color:var(--mut);margin-top:4px">Controle de parcelas, recebimentos parciais e baixas.</div></div></div><div class="grid3"><div class="metric"><div class="label">Saldo a receber</div><div class="value green">${money(aberto)}</div></div><div class="metric"><div class="label">Vencido</div><div class="value red">${money(venc)}</div></div><div class="metric"><div class="label">Baixas registradas</div><div class="value blue">${A('baixasReceber').length}</div></div></div><div style="overflow:auto"><table class="table"><thead><tr><th>Vencimento</th><th>Cliente / descrição</th><th>Original</th><th>Pago</th><th>Saldo</th><th>Status</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">Nenhuma conta a receber.</td></tr>'}</tbody></table></div></div>`}
const contas0=window.contas;if(typeof contas0==='function'){window.contas=function(){const r=contas0.apply(this,arguments),b=document.getElementById('p-contas');if(b&&!document.getElementById('v170-receber'))b.insertAdjacentHTML('afterbegin',blocoReceber());return r}};

/* ===== TRAVA DO CAIXA FECHADO ===== */
const smc0=window.saveMovimentacaoCaixa;if(typeof smc0==='function'){window.saveMovimentacaoCaixa=function(){const d=(document.getElementById('mc_data')||{}).value||today();if(fechado(d))return alert('O caixa de '+br(d)+' está fechado. Reabra o fechamento antes de lançar ou alterar movimentações.');return smc0.apply(this,arguments)}};
const emc0=window.excluirMovimentacaoManual;if(typeof emc0==='function'){window.excluirMovimentacaoManual=function(id){const m=A('caixa').find(x=>String(x.id)===String(id));if(m&&fechado(m.data))return alert('O caixa de '+br(m.data)+' está fechado. Reabra o fechamento antes de excluir esta movimentação.');return emc0.apply(this,arguments)}};

/* ===== MOVIMENTACOES DE ESTOQUE ===== */
function blocoEstoque(){const rows=A('movEstoque').slice().sort((a,b)=>(b.dataHora||'').localeCompare(a.dataHora||'')).slice(0,100).map(m=>`<tr><td>${br(m.data)}</td><td>${E(m.produto)}</td><td>${E(m.tipo)}</td><td>${N(m.quantidade)}</td><td>${N(m.saldoAnterior)}</td><td>${N(m.saldoNovo)}</td><td>${E(m.usuario||'—')}</td></tr>`).join('');return `<div class="card" id="v170-mov-est"><div class="head"><div><h3>📦 Histórico de movimentações do estoque</h3><div style="color:var(--mut);margin-top:4px">Entradas, vendas, devoluções e ajustes identificados pelas alterações de quantidade.</div></div><span class="pill">${A('movEstoque').length} registros</span></div><div style="overflow:auto"><table class="table"><thead><tr><th>Data</th><th>Produto</th><th>Movimento</th><th>Qtd.</th><th>Antes</th><th>Depois</th><th>Usuário</th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">As novas movimentações começarão a ser registradas a partir da V17.</td></tr>'}</tbody></table></div></div>`}
const est0=window.estoque;if(typeof est0==='function'){window.estoque=function(){const r=est0.apply(this,arguments),b=document.getElementById('p-estoque');if(b&&!document.getElementById('v170-mov-est'))b.insertAdjacentHTML('beforeend',blocoEstoque());return r}};

/* ===== DASHBOARD GERENCIAL ===== */
function blocoGestao(){const mes=today().slice(0,7),vs=A('vendas').filter(v=>vendaValida(v)&&String(v.data||'').slice(0,7)===mes),fat=vs.reduce((a,v)=>a+N(v.total),0),custo=vs.reduce((a,v)=>a+custoVenda(v),0),lucro=fat-custo,ticket=vs.length?fat/vs.length:0,margem=fat?lucro/fat*100:0;const rec=A('contas').filter(c=>c.tipo==='A Receber'&&String(c.status||'').toLowerCase()!=='pago'&&String(c.status||'').toLowerCase()!=='cancelada').reduce((a,c)=>a+Math.max(0,N(c.valorOriginal||c.valor)-N(c.valorPago)),0);let map={};vs.forEach(v=>(v.itens||[]).forEach(i=>{let k=i.nome||i.desc||'Item';map[k]=(map[k]||0)+N(i.qtd||1)}));const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,q],i)=>`<tr><td>${i+1}º</td><td>${E(k)}</td><td><b>${q}</b></td></tr>`).join('');return `<div class="card" id="v170-gestao"><div class="head"><div><h3>📊 Gestão V17 — resultado do mês</h3><div style="color:var(--mut);margin-top:4px">Indicadores calculados apenas com vendas não canceladas.</div></div></div><div class="grid4"><div class="metric"><div class="label">Faturamento</div><div class="value green">${money(fat)}</div></div><div class="metric"><div class="label">Custo estimado</div><div class="value red">${money(custo)}</div></div><div class="metric"><div class="label">Lucro bruto estimado</div><div class="value ${lucro>=0?'green':'red'}">${money(lucro)}</div></div><div class="metric"><div class="label">Margem bruta</div><div class="value gold">${margem.toFixed(1)}%</div></div></div><div class="grid3"><div class="metric"><div class="label">Ticket médio</div><div class="value blue">${money(ticket)}</div></div><div class="metric"><div class="label">Vendas no mês</div><div class="value">${vs.length}</div></div><div class="metric"><div class="label">A receber aberto</div><div class="value gold">${money(rec)}</div></div></div><div class="card"><h3>🏆 Produtos / serviços mais vendidos no mês</h3><table class="table"><thead><tr><th>#</th><th>Item</th><th>Qtd.</th></tr></thead><tbody>${top||'<tr><td colspan="3" class="empty">Sem vendas no mês.</td></tr>'}</tbody></table></div></div>`}
const dash0=window.dashboard;if(typeof dash0==='function'){window.dashboard=function(){const r=dash0.apply(this,arguments),b=document.getElementById('p-dashboard');if(b&&!document.getElementById('v170-gestao'))b.insertAdjacentHTML('afterbegin',blocoGestao());return r}};

/* ===== DIAGNOSTICO ===== */
window.v170Diagnostico=function(){const checks=[];const ok=(nome,cond,det)=>checks.push({nome,ok:!!cond,det});ok('Clientes',Array.isArray(st.clientes),A('clientes').length+' cadastrados');ok('Estoque',Array.isArray(st.estoque),A('estoque').length+' produtos');ok('Vendas',Array.isArray(st.vendas),A('vendas').length+' vendas');ok('OS',Array.isArray(st.os),A('os').length+' ordens');ok('Caixa',Array.isArray(st.caixa),A('caixa').length+' movimentos');ok('Contas',Array.isArray(st.contas),A('contas').length+' registros');ok('Nuvem Firebase',typeof cloudOK!=='undefined'&&cloudOK,typeof cloudOK!=='undefined'&&cloudOK?'conectada/configurada':'não confirmada');const ids=[...A('clientes'),...A('estoque'),...A('vendas'),...A('os')].map(x=>x&&x.id).filter(Boolean);ok('IDs duplicados',new Set(ids).size===ids.length,(ids.length-new Set(ids).size)+' duplicado(s)');const neg=A('estoque').filter(p=>N(p.qtd)<0);ok('Estoque negativo',neg.length===0,neg.length+' produto(s)');const semQuadro=A('bikes').filter(b=>!b.quadro);ok('Bikes sem número de quadro',semQuadro.length===0,semQuadro.length+' registro(s)');const resumo=checks.map(c=>`<tr><td>${c.ok?'✅':'⚠️'}</td><td><b>${E(c.nome)}</b></td><td>${E(c.det)}</td></tr>`).join('');modal(`<div class="mhead"><h3>Diagnóstico do sistema — V17</h3><button class="btn" onclick="closeM()">Fechar</button></div><div class="notice">Execute este diagnóstico depois de atualizações ou quando alguma tela apresentar comportamento inesperado.</div><table class="table"><thead><tr><th></th><th>Teste</th><th>Resultado</th></tr></thead><tbody>${resumo}</tbody></table><div class="actions"><button class="btn goldbtn" onclick="location.reload()">Recarregar sistema</button></div>`)};
const cfg0=window.config;if(typeof cfg0==='function'){window.config=function(){const r=cfg0.apply(this,arguments),b=document.getElementById('p-config');if(b&&!document.getElementById('v170-seguranca'))b.insertAdjacentHTML('beforeend',`<div class="card" id="v170-seguranca"><div class="head"><div><h3>🛡️ Segurança e manutenção — V17</h3><div style="color:var(--mut);margin-top:4px">Backup automático local a cada 30 minutos de uso e diagnóstico interno dos principais módulos.</div></div><span class="pill">V17</span></div><div class="actions"><button class="btn goldbtn" onclick="v170Diagnostico()">Executar diagnóstico</button><button class="btn" onclick="v170BaixarUltimoAutoBackup()">Baixar último backup automático</button></div></div>`);return r}};

autoBackup();
})();