/* May Bike ERP V18.0 - CRM aniversários e revisões */
(function(){'use strict';
const E=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const hoje=()=>typeof today==='function'?today():new Date().toISOString().slice(0,10);
function A(k){if(!Array.isArray(st[k]))st[k]=[];return st[k]}
function addDays2(d,n){if(typeof addDays==='function')return addDays(d,n);const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+Number(n||0));return x.toISOString().slice(0,10)}
function diff(d){return Math.round((new Date(d+'T12:00:00')-new Date(hoje()+'T12:00:00'))/86400000)}
function wpp(c,msg){const f=String(c.whats||c.whatsapp||'').replace(/\D/g,'');if(!f)return alert('Cliente sem WhatsApp cadastrado.');window.open('https://wa.me/'+(f.startsWith('55')?f:'55'+f)+'?text='+encodeURIComponent(msg),'_blank')}
window.v18WhatsAniversario=function(id){const c=A('clientes').find(x=>String(x.id)===String(id));if(c)wpp(c,'Olá, '+c.nome+'! A May Bike deseja um feliz aniversário! 🎉🚲 Preparamos nosso carinho especial para você. Esperamos te ver em breve!')};
window.v18WhatsRevisao=function(nome){const c=A('clientes').find(x=>String(x.nome)===String(nome));if(c)wpp(c,'Olá, '+c.nome+'! Aqui é da May Bike. Está chegando o período recomendado para revisão da sua bike. Quer agendar um horário com a gente?')};

/* acrescenta data de nascimento ao cadastro de cliente sem mexer nos campos existentes */
const open0=window.openCliente||((typeof openCliente==='function')?openCliente:null);
if(typeof open0==='function'){window.openCliente=function(id){open0(id);setTimeout(()=>{const c=A('clientes').find(x=>String(x.id)===String(id))||{},modalEl=document.getElementById('modal');if(!modalEl||document.getElementById('v18_nasc'))return;const obs=document.getElementById('c_obs')?.closest('.field');if(!obs)return;const d=document.createElement('div');d.className='field';d.innerHTML=`<label>Data de nascimento</label><input id="v18_nasc" type="date" value="${E(c.nascimento||c.dataNascimento||'')}">`;obs.parentNode.insertBefore(d,obs)},0)}}
const save0=window.saveCliente||((typeof saveCliente==='function')?saveCliente:null);
if(typeof save0==='function'){window.saveCliente=function(id){const nasc=document.getElementById('v18_nasc')?.value||'',nome=document.getElementById('c_nome')?.value||'',r=save0(id);setTimeout(()=>{const c=id?A('clientes').find(x=>String(x.id)===String(id)):A('clientes').slice().reverse().find(x=>String(x.nome||'')===String(nome));if(c&&nasc&&c.nascimento!==nasc){c.nascimento=nasc;Promise.resolve(save()).catch(()=>{})}},60);return r}}

function revisoes(){const dias=Number((st.config||{}).revisaoDias||120),map={};A('os').filter(o=>o.status!=='Cancelada').forEach(o=>{if(!o.cliente||!o.data)return;const k=String(o.cliente).toLocaleLowerCase('pt-BR'),d=o.proximaRevisao||o.revisaoEm||addDays2(o.data,dias);if(!map[k]||String(o.data)>String(map[k].base||''))map[k]={cliente:o.cliente,bike:o.bike||'Bicicleta',data:d,base:o.data}});return Object.values(map).sort((a,b)=>String(a.data).localeCompare(String(b.data)))}
function cardsDashboard(){const box=document.getElementById('p-dashboard');if(!box||document.getElementById('v18-crm-dash'))return;const mes=hoje().slice(5,7),aniv=A('clientes').filter(c=>String(c.nascimento||c.dataNascimento||'').slice(5,7)===mes).sort((a,b)=>String(a.nascimento||'').slice(5).localeCompare(String(b.nascimento||'').slice(5))).slice(0,10);const rev=revisoes().filter(r=>diff(r.data)<=30).slice(0,10);const arows=aniv.map(c=>`<tr><td><b>${E(c.nome)}</b></td><td>${String(c.nascimento||c.dataNascimento).slice(8,10)}/${mes}</td><td><button class="btn sm" onclick="v18WhatsAniversario('${E(c.id)}')">WhatsApp</button></td></tr>`).join('');const rrows=rev.map(r=>`<tr><td><b>${E(r.cliente)}</b></td><td>${E(r.bike)}</td><td>${typeof br==='function'?br(r.data):E(r.data)}</td><td>${diff(r.data)<0?'<span class="badge b5">Atrasada</span>':'<span class="badge b2">Próxima</span>'}</td><td><button class="btn sm" onclick="v18WhatsRevisao('${E(r.cliente)}')">WhatsApp</button></td></tr>`).join('');const d=document.createElement('div');d.id='v18-crm-dash';d.className='grid2';d.innerHTML=`<div class="card"><div class="head"><h3>🎂 Aniversariantes do mês</h3><span class="pill">${aniv.length}</span></div><table class="table"><thead><tr><th>Cliente</th><th>Data</th><th></th></tr></thead><tbody>${arows||'<tr><td colspan="3" class="empty">Nenhum aniversário cadastrado neste mês.</td></tr>'}</tbody></table></div><div class="card"><div class="head"><h3>🔔 Revisões vencidas / próximos 30 dias</h3><span class="pill">${rev.length}</span></div><table class="table"><thead><tr><th>Cliente</th><th>Bike</th><th>Data</th><th>Status</th><th></th></tr></thead><tbody>${rrows||'<tr><td colspan="5" class="empty">Nenhuma revisão pendente.</td></tr>'}</tbody></table></div>`;box.appendChild(d)}
const dash0=window.dashboard||((typeof dashboard==='function')?dashboard:null);if(typeof dash0==='function'){window.dashboard=function(){const r=dash0();setTimeout(cardsDashboard,0);return r}}
const render0=render;render=function(p){const r=render0(p);if(p==='dashboard')setTimeout(cardsDashboard,0);return r};
})();