/* May Bike ERP V18.0 - Recibos Manuais */
(function(){'use strict';
const N=v=>Number(String(v==null?'':v).replace(',','.'))||0;
const E=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const V=id=>{const e=document.getElementById(id);return e?e.value:''};
const M=v=>typeof money==='function'?money(v):('R$ '+N(v).toLocaleString('pt-BR',{minimumFractionDigits:2}));
const hoje=()=>typeof today==='function'?today():new Date().toISOString().slice(0,10);
const uid2=()=>typeof uid==='function'?uid():Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function A(k){if(!Array.isArray(st[k]))st[k]=[];return st[k]}
A('recibosManuais');st.seqReciboManual=Math.max(1,Number(st.seqReciboManual||1));
const pad=n=>String(n).padStart(6,'0');
function cliId(id){return A('clientes').find(c=>String(c.id)===String(id))||null}
function opts(){return A('clientes').slice().sort((a,b)=>String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR',{sensitivity:'base'})).map(c=>`<option value="${E(c.id)}">${E(c.nome||'Sem nome')}</option>`).join('')}
function ext(v){const n=Math.floor(N(v)),c=Math.round((N(v)-n)*100);const base=n===0?'zero':n===1?'um':n===2?'dois':n===3?'três':n===4?'quatro':n===5?'cinco':n===10?'dez':n===20?'vinte':n===50?'cinquenta':n===100?'cem':String(n);return base+' '+(n===1?'real':'reais')+(c?(' e '+c+' centavos'):'')}
window.v18CriarReciboInterno=function(d){const num=st.seqReciboManual++;const r={id:uid2(),num,cod:'RM'+pad(num),data:hoje(),clienteId:d.clienteId||'',cliente:d.cliente||'',valor:N(d.valor),forma:d.forma||'',referencia:d.referencia||'',lancarCaixa:!!d.lancarCaixa,origem:d.origem||'Manual',status:'Ativo',criadoEm:new Date().toISOString()};A('recibosManuais').push(r);return r};
window.v18OpenRecibo=function(){modal(`<div class="mhead"><h3>Novo recibo manual</h3><button class="btn" onclick="closeM()">Fechar</button></div><div class="form3"><div class="field"><label>Cliente cadastrado</label><select id="v18r_cli" onchange="v18ReciboCliente()"><option value="">Nome avulso</option>${opts()}</select></div><div class="field"><label>Nome do pagador *</label><input id="v18r_nome"></div><div class="field"><label>Valor *</label><input id="v18r_valor" type="number" min="0.01" step="0.01"></div><div class="field"><label>Forma de pagamento</label><select id="v18r_forma"><option>PIX</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Transferência</option><option>Outro</option></select></div></div><div class="field"><label>Referente a *</label><input id="v18r_ref" placeholder="Ex.: entrada da bicicleta, pagamento de serviço..."></div><label style="display:flex;gap:8px;align-items:center;margin-top:10px"><input id="v18r_caixa" type="checkbox" style="width:auto"> Lançar este recebimento no Caixa</label><div class="notice" style="margin-top:10px">Marque Caixa somente se este valor ainda não foi registrado por venda, OS ou crédito.</div><div class="actions"><button class="btn goldbtn" onclick="v18SalvarRecibo()">Gerar recibo</button></div>`)};
window.v18ReciboCliente=function(){const c=cliId(V('v18r_cli')),e=document.getElementById('v18r_nome');if(e&&c)e.value=c.nome||''};
window.v18SalvarRecibo=async function(){const c=cliId(V('v18r_cli')),nome=(V('v18r_nome')||(c&&c.nome)||'').trim(),valor=N(V('v18r_valor')),forma=V('v18r_forma'),ref=V('v18r_ref').trim(),cx=!!document.getElementById('v18r_caixa')?.checked;if(!nome)return alert('Informe o nome do pagador.');if(valor<=0)return alert('Informe um valor maior que zero.');if(!ref)return alert('Informe a que se refere o recibo.');const r=window.v18CriarReciboInterno({clienteId:c?c.id:'',cliente:nome,valor,forma,referencia:ref,lancarCaixa:cx,origem:'Manual'});if(cx)A('caixa').push({id:uid2(),data:hoje(),tipo:'Entrada',desc:r.cod+' - '+nome+' - '+ref,cat:'Recibo manual',valor,forma,reciboManualId:r.id});if(typeof logAudit==='function')logAudit('Recibo manual criado',r.cod+' / '+nome+' / '+M(valor));closeM();await Promise.resolve(save());if(typeof go==='function')go('recibos');setTimeout(()=>window.v18PrintReciboManual(r.id),150)};
window.v18CancelarRecibo=async function(id){const r=A('recibosManuais').find(x=>String(x.id)===String(id));if(!r||r.status==='Cancelado')return;if(!confirm('Cancelar '+r.cod+'? O recibo permanecerá no histórico.'))return;r.status='Cancelado';r.canceladoEm=new Date().toISOString();if(r.lancarCaixa&&!r.estornoCaixa){A('caixa').push({id:uid2(),data:hoje(),tipo:'Saída',desc:'Estorno '+r.cod+' - '+r.cliente,cat:'Cancelamento de recibo',valor:N(r.valor),forma:r.forma,reciboManualId:r.id});r.estornoCaixa=true}if(typeof logAudit==='function')logAudit('Recibo manual cancelado',r.cod+' / '+r.cliente);await Promise.resolve(save());go('recibos')};
window.v18PrintReciboManual=function(id){const r=A('recibosManuais').find(x=>String(x.id)===String(id));if(!r)return alert('Recibo não encontrado.');const cancel=r.status==='Cancelado'?'<div style="font-size:38px;color:#b00020;font-weight:900;text-align:center;border:3px solid #b00020;padding:8px;margin:12px 0">CANCELADO</div>':'';const html=`<!doctype html><html><head><meta charset="utf-8"><title>${E(r.cod)}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial;color:#171717;margin:0}.cab{display:flex;align-items:center;gap:20px;border-bottom:3px solid #e5ad13;padding-bottom:14px}.cab img{width:190px;max-height:82px;object-fit:contain}.dados{font-size:12px;line-height:1.5;margin-left:auto;text-align:right}.titulo{text-align:center;margin:24px 0 18px}.box{border:1px solid #bbb;border-radius:10px;padding:20px;font-size:16px;line-height:1.75}.valor{font-size:24px;font-weight:800}.ass{display:grid;grid-template-columns:1fr 1fr;gap:60px;margin-top:70px;text-align:center}.linha{border-top:1px solid #222;padding-top:8px}.rod{text-align:center;font-size:11px;margin-top:45px;color:#555}</style></head><body><div class="cab"><img src="icons/maybike-logo-horizontal.png"><div class="dados"><b>May Bike — Loja & Oficina</b><br>Rua Marechal Floriano Peixoto, 395 - Centro<br>União da Vitória/PR<br>(42) 98842-5435 • maybikee@gmail.com</div></div>${cancel}<div class="titulo"><h1>RECIBO ${E(r.cod)}</h1><div>Data: ${typeof br==='function'?br(r.data):E(r.data)}</div></div><div class="box">Recebemos de <b>${E(r.cliente)}</b> a importância de <span class="valor">${M(r.valor)}</span> (${E(ext(r.valor))}), referente a <b>${E(r.referencia)}</b>.<br><br><b>Forma de pagamento:</b> ${E(r.forma||'Não informada')}</div><div class="ass"><div class="linha">Assinatura do cliente</div><div class="linha">May Bike</div></div><div class="rod">Sua bike. Seu estilo. • Documento ${E(r.cod)}</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;const w=window.open('','_blank','width=900,height=1000');if(!w)return alert('Permita pop-ups para imprimir o recibo.');w.document.open();w.document.write(html);w.document.close()};
function page(){const q=(document.getElementById('v18r_busca')?.value||'').toLocaleLowerCase('pt-BR');const arr=A('recibosManuais').slice().sort((a,b)=>String(b.criadoEm||b.data).localeCompare(String(a.criadoEm||a.data))).filter(r=>!q||[r.cod,r.cliente,r.referencia,r.forma].some(v=>String(v||'').toLocaleLowerCase('pt-BR').includes(q)));const rows=arr.map(r=>`<tr><td><b>${E(r.cod)}</b></td><td>${typeof br==='function'?br(r.data):E(r.data)}</td><td>${E(r.cliente)}</td><td>${E(r.referencia)}</td><td>${E(r.forma||'—')}</td><td><b>${M(r.valor)}</b></td><td>${r.status==='Cancelado'?'<span class="badge b5">Cancelado</span>':'<span class="badge b3">Ativo</span>'}</td><td><button class="btn sm" onclick="v18PrintReciboManual('${E(r.id)}')">Imprimir</button> ${r.status!=='Cancelado'?`<button class="btn redbtn sm" onclick="v18CancelarRecibo('${E(r.id)}')">Cancelar</button>`:''}</td></tr>`).join('');$('p-recibos').innerHTML=`<div class="card"><div class="head"><div><h3>Recibos Manuais</h3><div style="color:var(--mut)">Recibos numerados, pesquisáveis e reimprimíveis.</div></div><button class="btn goldbtn" onclick="v18OpenRecibo()">+ Novo recibo</button></div><div class="field"><label>Pesquisar</label><input id="v18r_busca" placeholder="Número, cliente, referência ou forma" oninput="v18RecibosPage()" value="${E(q)}"></div><div style="overflow:auto"><table class="table"><thead><tr><th>Nº</th><th>Data</th><th>Cliente</th><th>Referente</th><th>Forma</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty">Nenhum recibo manual emitido.</td></tr>'}</tbody></table></div></div>`}
window.v18RecibosPage=page;
try{if(typeof pages!=='undefined'&&!pages.some(p=>p[0]==='recibos')){const i=pages.findIndex(p=>p[0]==='creditos');pages.splice(i<0?pages.length:i+1,0,['recibos','🧾 Recibos Manuais']);}}catch(e){console.warn(e)}
const render0=render;render=function(p){if(p==='recibos')return page();return render0(p)};
})();